### ISSUE TITLE
[Issue] MySQL module doesn't saves correctly equip value

### ISSUE THREAD

**Issue by chocochocotorta** [Batfoxkid/Text-Store#9]
Using the TextStore MySQL module works great, equipping a item and disconnecting to save changes the item `equip` value to 1 in the common_items table which works for the UseThisItem void, but when unequipped and disconnecting, the value doesn't changes to 0.
I don't know if this is because of the module or caused by how the things are saved, since with the default TextStore the items never gets saved (equiping it manually, the player item returns to zero when it connects).

**Comment by Batfoxkid** [comment]
Related to #7?

**Comment by chocochocotorta** [comment]
> Related to #7?

Could be, but i'm not really sure since in the #7 issue the problem is that the store never equips the item even if it appears as equipped in the player data and here i reported that the equip data doesn't saves well (on MySQL, but could be too in default)
